<?php

if(!defined("INSIDE")){ die("attemp hacking"); }
 
define('INSIDE'  , true );
define('INSTALL' , false);

includeLang('fleetcontrol');
include($rocketnova_root_path . 'includes/functions/FlyingFleetHandler.'.$phpEx);
include($rocketnova_root_path . 'includes/functions/func.ban.'.$phpEx);
include($rocketnova_root_path . 'includes/functions/MissionCaseAttack.'.$phpEx);
include($rocketnova_root_path . 'includes/functions/MissionCaseStay.'.$phpEx);
include($rocketnova_root_path . 'includes/functions/MissionCaseStayAlly.'.$phpEx);
include($rocketnova_root_path . 'includes/functions/MissionCaseTransport.'.$phpEx);
include($rocketnova_root_path . 'includes/functions/MissionCaseSpy.'.$phpEx);
include($rocketnova_root_path . 'includes/functions/MissionCaseRecycling.'.$phpEx);
include($rocketnova_root_path . 'includes/functions/MissionCaseDestruction.'.$phpEx);
include($rocketnova_root_path . 'includes/functions/MissionCaseColonisation.'.$phpEx);
include($rocketnova_root_path . 'includes/functions/MissionCaseSave.'.$phpEx);
include($rocketnova_root_path . 'includes/functions/MissionCaseExpedition.'.$phpEx);
include($rocketnova_root_path . 'includes/functions/SendSimpleMessage.'.$phpEx);
include($rocketnova_root_path . 'includes/functions/SendSimpleMessage2.'.$phpEx);
include($rocketnova_root_path . 'includes/functions/SpyTarget.'.$phpEx);
include($rocketnova_root_path . 'includes/functions/RestoreFleetToPlanet.'.$phpEx);
include($rocketnova_root_path . 'includes/functions/StoreGoodsToPlanet.'.$phpEx);
include($rocketnova_root_path . 'includes/functions/CheckPlanetBuildingQueue.'.$phpEx);
include($rocketnova_root_path . 'includes/functions/CheckPlanetUsedFields.'.$phpEx);
include($rocketnova_root_path . 'includes/functions/CreateOneMoonRecord.'.$phpEx);
include($rocketnova_root_path . 'includes/functions/CreateOnePlanetRecord.'.$phpEx);
include($rocketnova_root_path . 'includes/functions/InsertJavaScriptChronoApplet.'.$phpEx);
include($rocketnova_root_path . 'includes/functions/IsTechnologieAccessible.'.$phpEx);
include($rocketnova_root_path . 'includes/functions/GetBuildingTime.'.$phpEx);
include($rocketnova_root_path . 'includes/functions/GetRestPrice.'.$phpEx);
include($rocketnova_root_path . 'includes/functions/GetElementPrice.'.$phpEx);
include($rocketnova_root_path . 'includes/functions/GetBuildingPrice.'.$phpEx);
include($rocketnova_root_path . 'includes/functions/IsElementBuyable.'.$phpEx);
include($rocketnova_root_path . 'includes/functions/CheckCookies.'.$phpEx);
include($rocketnova_root_path . 'includes/functions/CheckUser.'.$phpEx);
include($rocketnova_root_path . 'includes/functions/InsertGalaxyScripts.'.$phpEx);
include($rocketnova_root_path . 'includes/functions/GalaxyCheckFunctions.'.$phpEx);
include($rocketnova_root_path . 'includes/functions/ShowGalaxyRows.'.$phpEx);
include($rocketnova_root_path . 'includes/functions/GetPhalanxRange.'.$phpEx);
include($rocketnova_root_path . 'includes/functions/GetMissileRange.'.$phpEx);
include($rocketnova_root_path . 'includes/functions/GalaxyRowPos.'.$phpEx);
include($rocketnova_root_path . 'includes/functions/GalaxyRowPlanet.'.$phpEx);
include($rocketnova_root_path . 'includes/functions/GalaxyRowPlanetName.'.$phpEx);
include($rocketnova_root_path . 'includes/functions/GalaxyRowMoon.'.$phpEx);
include($rocketnova_root_path . 'includes/functions/GalaxyRowDebris.'.$phpEx);
include($rocketnova_root_path . 'includes/functions/GalaxyRowUser.'.$phpEx);
include($rocketnova_root_path . 'includes/functions/GalaxyRowava.'.$phpEx);
include($rocketnova_root_path . 'includes/functions/GalaxyRowAlly.'.$phpEx);
include($rocketnova_root_path . 'includes/functions/GalaxyRowActions.'.$phpEx);
include($rocketnova_root_path . 'includes/functions/ShowGalaxySelector.'.$phpEx);
include($rocketnova_root_path . 'includes/functions/ShowGalaxyMISelector.'.$phpEx);
include($rocketnova_root_path . 'includes/functions/ShowGalaxyTitles.'.$phpEx);
include($rocketnova_root_path . 'includes/functions/GalaxyLegendPopup.'.$phpEx);
include($rocketnova_root_path . 'includes/functions/ShowGalaxyFooter.'.$phpEx);
include($rocketnova_root_path . 'includes/functions/GetMaxConstructibleElements.'.$phpEx);
include($rocketnova_root_path . 'includes/functions/GetElementRessources.'.$phpEx);
include($rocketnova_root_path . 'includes/functions/ElementBuildListBox.'.$phpEx);
include($rocketnova_root_path . 'includes/functions/ElementBuildListQueue.'.$phpEx);
include($rocketnova_root_path . 'includes/functions/FleetBuildingPage.'.$phpEx);
include($rocketnova_root_path . 'includes/functions/DefensesBuildingPage.'.$phpEx);
include($rocketnova_root_path . 'includes/functions/ResearchBuildingPage.'.$phpEx);
include($rocketnova_root_path . 'includes/functions/BatimentBuildingPage.'.$phpEx);
include($rocketnova_root_path . 'includes/functions/CheckLabSettingsInQueue.'.$phpEx);
include($rocketnova_root_path . 'includes/functions/InsertBuildListScript.'.$phpEx);
include($rocketnova_root_path . 'includes/functions/AddBuildingToQueue.'.$phpEx);
include($rocketnova_root_path . 'includes/functions/ShowBuildingQueue.'.$phpEx);
include($rocketnova_root_path . 'includes/functions/HandleTechnologieBuild.'.$phpEx);
include($rocketnova_root_path . 'includes/functions/BuildingSavePlanetRecord.'.$phpEx);
include($rocketnova_root_path . 'includes/functions/BuildingSaveUserRecord.'.$phpEx);
include($rocketnova_root_path . 'includes/functions/RemoveBuildingFromQueue.'.$phpEx);
include($rocketnova_root_path . 'includes/functions/CancelBuildingFromQueue.'.$phpEx);
include($rocketnova_root_path . 'includes/functions/SetNextQueueElementOnTop.'.$phpEx);
include($rocketnova_root_path . 'includes/functions/ShowTopNavigationBar.'.$phpEx);
include($rocketnova_root_path . 'includes/functions/SetSelectedPlanet.'.$phpEx);
include($rocketnova_root_path . 'includes/functions/MessageForm.'.$phpEx);
include($rocketnova_root_path . 'includes/functions/PlanetResourceUpdate.'.$phpEx);
include($rocketnova_root_path . 'includes/functions/BuildFlyingFleetTable.'.$phpEx);
include($rocketnova_root_path . 'includes/functions/SendNewPassword.'.$phpEx);
include($rocketnova_root_path . 'includes/functions/HandleElementBuildingQueue.'.$phpEx);
include($rocketnova_root_path . 'includes/functions/UpdatePlanetBatimentQueueList.'.$phpEx);
include($rocketnova_root_path . 'includes/functions/IsOfficierAccessible.'.$phpEx);
include($rocketnova_root_path . 'includes/functions/CheckInputStrings.'.$phpEx);
include($rocketnova_root_path . 'includes/functions/MipCombatEngine.'.$phpEx);
include($rocketnova_root_path . 'includes/functions/DeleteSelectedUser.'.$phpEx);
include($rocketnova_root_path . 'includes/functions/SortUserPlanets.'.$phpEx);
include($rocketnova_root_path . 'includes/functions/BuildFleetEventTable.'.$phpEx);
include($rocketnova_root_path . 'includes/functions/GetMaxConstructibleShips.'.$phpEx);
include($rocketnova_root_path . 'includes/functions/AbandonColony.'.$phpEx);
include($rocketnova_root_path . 'includes/functions/SessionFunctions.'.$phpEx);
include($rocketnova_root_path . 'includes/calculateAttack.'.$phpEx);
include($rocketnova_root_path . 'includes/formatCR.'.$phpEx);


?>