<?php

$lang['Titel']     												= 'Tutorial zum Spiel';
$lang['TitelGame']     										= 'RocketNova';

$lang['welcome']     											= 'Willkommen in den unendlichen Weiten von';
$lang['tutorial_back']     								= '<p align="center"><a href="tutorial.php">Zur&uuml;ck zum Inhaltsverzeichnis</a></p>';

$lang['tutorial_Titel']     							= 'Inhaltsverzeichnis';
$lang['tutorial_teil1']     							= 'Das Architektursystem';
$lang['tutorial_teil2']     							= 'Die Forschungseinrichtung';
$lang['tutorial_teil3']     							= 'Die Raumschiffswerft';
$lang['tutorial_teil4']     							= 'Die Verteidigunganlage';
$lang['tutorial_teil5']     							= 'Galaxieansicht, Flotten versenden und Verteidigung';
$lang['tutorial_teil6']     							= 'Das Lexikon mit gebr&auml;uchlichen Abk&uuml;rzungen';
$lang['tutorial_teil7']     							= 'Das Saven';
$lang['tutorial_teil8']     							= 'Die Angriffszonen';

$lang['tutorial_go_teil1']     						= 'Tutorial Teil 1';
$lang['tutorial_go_teil2']     						= 'Tutorial Teil 2';
$lang['tutorial_go_teil3']     						= 'Tutorial Teil 3';
$lang['tutorial_go_teil4']     						= 'Tutorial Teil 4';
$lang['tutorial_go_teil5']     						= 'Tutorial Teil 5';
$lang['tutorial_go_teil6']     						= 'Tutorial Teil 6';
$lang['tutorial_go_teil7']     						= 'Tutorial Teil 7';
$lang['tutorial_go_teil8']     						= 'Tutorial Teil 8';

//Tutorial 1 Anzeige--------------------------------------------------------------------------------------------------------
$lang['tutorial_teil1_info1']     				= 'Tutorial Teil 1';
$lang['tutorial_teil1_info2']     				= 'Hier findest du alles was du &uuml;ber das Architektursystem wissen musst.';
$lang['tutorial_teil1_info3']     				= 'Die Aluminiummine';
$lang['tutorial_teil1_info4']     				= 'Hauptrohstofflieferanten f&uuml;r den Bau tragender Strukturen von Bauwerken und Schiffen. Aluminium ist der billigste Rohstoff, daf&uuml;r wird er mehr ben&ouml;tigt als die anderen. Aluminium braucht zur Herstellung am wenigsten Energie. Je gr&ouml;&szlig;er die Minen ausgebaut sind, desto tiefer sind sie. Bei den meisten Planeten befindet sich das Aluminium in gro&szlig;er Tiefe, durch diese tieferen Minen k&ouml;nnen mehr Aluminium abgebaut werden, die Produktion steigt. Gleichzeitig muss f&uuml;r die gr&ouml;&szlig;ere Aluminiummine mehr Energie zur Verf&uuml;gung gestellt werden.';
$lang['tutorial_teil1_info5']     				= 'Die Siliciummine';
$lang['tutorial_teil1_info6']     				= 'Baut Mineralien ab die fuer die Feinelektronik benoetigt werden, sie benoetigt jedoch mehr da sie die Mineralien gleich in Noetigen Leggierungen verarbeitet.';
$lang['tutorial_teil1_info7']     				= 'Die Deuteriumfabrik';
$lang['tutorial_teil1_info8']     				= 'Deuterium ist schwerer Wasserstoff. Daher sind &auml;hnlich wie bei den Minen die gr&ouml;&szlig;ten Vorr&auml;te auf dem Grund des Meeres. Der Ausbau des Synthetisierers sorgt ebenfalls f&uuml;r die Erschlie&szlig;ung dieser Deuterium-Tiefenlagerst&auml;tten. Deuterium wird als Treibstoff f&uuml;r die Schiffe, f&uuml;r fast alle Forschungen, f&uuml;r einen Blick in die Galaxie sowie f&uuml;r den Sensorphalanx-Scan ben&ouml;tigt.';
$lang['tutorial_teil1_info9']     				= 'Das Solarkraftwerk';
$lang['tutorial_teil1_info10']     				= 'Um die Energie zur Versorgung der Minen und Synthetisierern zu gew&auml;hrleisten, sind riesige Solarkraftwerkanlagen von N&ouml;ten. Je gr&ouml;&szlig;er die Anlagen ausgebaut sind, desto mehr Oberfl&auml;che ist mit photovoltaischen Zellen bedeckt, welche Lichtenergie in elektrische Energie umwandeln. Solarkraftwerke stellen den Grundstock der planetaren Energieversorgung dar.';
$lang['tutorial_teil1_info11']     				= 'Das Atomkraftwerk';
$lang['tutorial_teil1_info12']     				= 'In den Atomkraftwerk werden Atome gespalten um so mehr energie erzeugen als in Solarkraftwerk. Ist jedoch sehr teuer im Bau.';
$lang['tutorial_teil1_info13']     				= 'Die Roboterfabrik';
$lang['tutorial_teil1_info14']     				= 'Roboterfabriken stellen einfache Arbeitskr&auml;fte zur Verf&uuml;gung, die beim Bau der planetaren Infrastruktur eingesetzt werden k&ouml;nnen. Jede Stufe erh&ouml;ht damit die Geschwindigkeit des Ausbaus von Geb&auml;uden.';
$lang['tutorial_teil1_info15']     				= 'Die Nanitenfabrik';
$lang['tutorial_teil1_info16']     				= 'Die Nanitenfabrik ist die Kr&ouml;nung der Robotertechnik. Naniten sind nanometergro&szlig;e Roboter, die durch Vernetzung zu au&szlig;erordentlichen Leistungen im Stande sind. Einmal erforscht erh&ouml;hen sie die Produktivit&auml;t in fast allen Bereichen. Die Nanitenfabrik halbiert pro Stufe die Bauzeit von Geb&auml;uden, Schiffen und Verteidigungsanlagen.';
$lang['tutorial_teil1_info17']     				= 'Die Waffenfabrik';
$lang['tutorial_teil1_info18']     				= 'In der planetaren Werft werden alle Arten von Schiffen und Verteidigungsanlagen gebaut. Je gr&ouml;&szlig;er sie ist, desto schneller k&ouml;nnen aufw&auml;ndigere und gr&ouml;&szlig;ere Schiffe und Verteidigungsanlagen gebaut werden. Durch Anbau einer Nanitenfabrik werden winzige Roboter erstellt, die den Arbeitern helfen, schneller zu arbeiten.';
$lang['tutorial_teil1_info19']     				= 'Der Aluminiumspeicher';
$lang['tutorial_teil1_info20']     				= 'Riesige Lagerst&auml;tte f&uuml;r abgebautes Aluminiumerz. Je gr&ouml;&szlig;er der Speicher, desto mehr Aluminium kann in ihm gelagert werden. Ist das Lager voll, wird kein Aluminium mehr abgebaut.';
$lang['tutorial_teil1_info21']     				= 'Der Siliciumspeicher';
$lang['tutorial_teil1_info22']     				= 'Das noch unbearbeitete Silicium wird in diesen riesigen Lagerhallen zwischengespeichert. Je gr&ouml;&szlig;er das Lager, desto mehr Silicium kann in ihm eingelagert werden. Sind die Siliciumlager voll, wird kein weiteres Silicium abgebaut.';
$lang['tutorial_teil1_info23']     				= 'Der Deuteriumtank';
$lang['tutorial_teil1_info24']     				= 'Riesige Tanks zur Lagerung des neu gewonnenen Deuteriums. Diese Lager findet man meistens in der N&auml;he von Raumh&auml;fen. Je gr&ouml;&szlig;er sie sind, desto mehr Deuterium kann in ihnen gelagert werden. Sind sie gef&uuml;llt, wird kein Deuterium mehr abgebaut.';
$lang['tutorial_teil1_info25']     				= 'Das Forschungslabor';
$lang['tutorial_teil1_info26']     				= 'Um neue Technologien zu erforschen, ist der Betrieb einer Forschungsstation notwendig. Die Ausbaustufe einer Forschungsstation ist ausschlaggebend daf&uuml;r, wie schnell eine neue Technologie erforscht werden kann. Je h&ouml;her die Ausbaustufe des Labors, umso mehr neue Technologien k&ouml;nnen erforscht werden. Um die Forschungsarbeiten m&ouml;glichst schnell zum Abschluss zu bringen, werden, wenn auf einem Planeten geforscht wird, automatisch alle verf&uuml;gbaren Forscher in diese Forschungsstation geschickt und stehen somit auf anderen Planeten nicht mehr zur Verf&uuml;gung. Sobald eine Technologie einmal erforscht ist, kehren die Forscher auf ihre Heimatplaneten zur&uuml;ck und bringen das Wissen um sie mit. So kann man die Technologie auf all seinen Planeten einsetzen.';
$lang['tutorial_teil1_info27']     				= 'Der Terraformer';
$lang['tutorial_teil1_info28']     				= 'Mit zunehmendem Ausbau der Planeten, wurde die Frage des begrenzten Lebensraums auf Kolonien immer wichtiger. Traditionelle Methoden wie Hoch- und Tiefbau erwiesen sich zunehmend als unzureichend. Eine kleine Gruppe von Hochenergiephysikern und Nanotechnikern fand schlie&szlig;lich die L&ouml;sung: Das TerraformingUnter Aufwand riesiger Energiemengen kann der Terraformer ganze Landstriche oder gar Kontinente urbar machen. In diesem Geb&auml;ude werden fortw&auml;hrend eigens daf&uuml;r konstruierte Naniten produziert, die f&uuml;r eine konstante Qualit&auml;t des Bodens sorgen.Einmal gebaut kann der Terraformer nicht wieder abgerissen werden.';
$lang['tutorial_teil1_info29']     				= 'Das Allianzdepot';
$lang['tutorial_teil1_info30']     				= 'Das Allianzdepot bietet die M&ouml;glichkeit, befreundete Flotten, die bei der Verteidigung helfen und im Orbit stehen, mit Treibstoff zu versorgen. F&uuml;r jeden Ausbaulevel des Allianzdepots k&ouml;nnen 10.000 Einheiten Deuterium pro Stunde an die zu versorgenden Flotten im Orbit geschickt werden.';
$lang['tutorial_teil1_info31']     				= 'Das Raketensilo';
$lang['tutorial_teil1_info32']     				= 'Raketensilos dienen zum Einlagern von Raketen. Pro ausgebauter Stufe kann man f&uuml;nf Interplanetar- oder zehn Abfangraketen einlagern. Eine Interplanetarrakete ben&ouml;tigt soviel Platz wie zwei Abfrangraketen. Unterschiedliche Raketentypen k&ouml;nnen beliebig kombiniert werden.';

//Tutorial 2 Anzeige--------------------------------------------------------------------------------------------------------
$lang['tutorial_teil2_info1']     				= 'Tutorial Teil 2';
$lang['tutorial_teil2_info2']     				= 'Hier findest du alles was du &uuml;ber die Forschungseinrichtung wissen musst.';
$lang['tutorial_teil2_info3']     				= 'Spionagetechnik';
$lang['tutorial_teil2_info4']     				= 'Die Spionagetechnik befasst sich in erster Linie mit der Erforschung neuer und effizienterer Sensoren. Je h&ouml;her diese Technik entwickelt ist, umso mehr Informationen stehen dem Nutzer &uuml;ber Vorg&auml;nge in seiner Umgebung zur Verf&uuml;gung. F&uuml;r Sonden ist die Differenz des eigenen und des gegnerischen Spionagelevels entscheidend. Je weiter die eigene Spionagetechnik erforscht ist, desto mehr Informationen enth&auml;lt der Bericht und um so kleiner ist die Chance , dass man beim Spionieren entdeckt wird. Je mehr Sonden man schickt, desto mehr Details erf&auml;hrt man von seinem Gegner, gleichzeitig steigt aber auch die Gefahr einer Entdeckung. Die Spionagetechnik verbessert ebenfalls die Ortung fremder Flotten. Dabei ist nur der eigene Spionagelevel entscheidend. Ab Level 2 wird zus&auml;tzlich zur reinen Angriffsmeldung auch die Gesamtanzahl der angreifenden Schiffe angezeigt. Ab Level 4 sieht man die Art der angreifenden Schiffe, sowie die Gesamtanzahl und ab Level 8 die genaue Anzahl der verschiedenen Schiffs-Typen. F&uuml;r Raider ist diese Technik unverzichtbar, da sie Auskunft dar&uuml;ber gibt, ob das Opfer Flotte und/oder Verteidigung stationiert hat oder nicht. Deshalb sollte diese Technik schon sehr fr&uuml;h erforscht werden. Am besten sofort nach der Erforschung von Kleinen Transportern.';
$lang['tutorial_teil2_info5']     				= 'Computertechnik';
$lang['tutorial_teil2_info6']     				= 'Die Computertechnik befasst sich mit der Erweiterung der vorhandenen Computerkapazit&auml;ten. Immer leistungsf&auml;higere und effizientere Computersysteme werden entwickelt. Die Rechenleistung steigt immer weiter und die Geschwindigkeit, mit denen Rechenprozesse ablaufen, wird ebenfalls erh&ouml;ht. Mit der Erh&ouml;hung der Computerkapazit&auml;ten lassen sich immer mehr Flotten gleichzeitig befehligen. Jede Stufe Computertechnik erh&ouml;ht dabei die maximale Flottenanzahl um eins. Je mehr Flotten man gleichzeitig verschicken kann, desto mehr kann man raiden und desto mehr Rohstoffe kann man einnehmen. Nat&uuml;rlich nutzt diese Technik auch H&auml;ndlern, denn sie k&ouml;nnen dann ebenfalls mehr Handelsflotten gleichzeitig losschicken. Aus diesem Grund sollte die Computertechnik kontinuierlich &uuml;ber das gesamte Spiel hinweg ausgebaut werden.';
$lang['tutorial_teil2_info7']     				= 'Waffentechnik';
$lang['tutorial_teil2_info8']     				= 'Die Waffentechnik besch&auml;ftigt sich vor allem mit der Weiterentwicklung bestehender Waffensysteme. Dabei wird insbesondere darauf Wert gelegt, die vorhandenen Systeme mit mehr Energie auszustatten und diese Energie punktgenauer zu kanalisieren. Dadurch werden die Waffensysteme effizienter und Waffen richten mehr Schaden an. Jede Stufe der Waffentechnik erh&ouml;ht die Waffenst&auml;rke der Einheiten um 10% des Grundwertes. Die Waffentechnik ist wichtig, um sp&auml;ter die eigenen Einheiten konkurrenzf&auml;hig zu halten. Deshalb sollte sie kontinuierlich das ganze Spiel hindurch entwickelt werden.';
$lang['tutorial_teil2_info9']     				= 'Schildtechnik';
$lang['tutorial_teil2_info10']     				= 'Die Schildtechnik besch&auml;ftigt sich mit der Erforschung immer neuer M&ouml;glichkeiten, die Schilde mit mehr Energie zu versorgen und sie so effizienter und belastbarer zu machen. Dadurch steigt mit jeder erforschten Stufe die Effizienz der Schilde um 10% des Grundwertes.';
$lang['tutorial_teil2_info11']     				= 'Raumschiffpanzerung';
$lang['tutorial_teil2_info12']     				= 'Spezielle Legierungen machen die Panzerung der Raumschiffe immer besser. Ist einmal eine sehr widerstandsf&auml;hige Legierung gefunden, wird durch spezielle Strahlungen die molekulare Struktur des Raumschiffes ver&auml;ndert und auf den Stand der besten erforschten Legierung gebracht. Die Wirksamkeit der Panzerung kann so pro Stufe um 10% des Grundwertes gesteigert werden.';
$lang['tutorial_teil2_info13']     				= 'Energietechnik';
$lang['tutorial_teil2_info14']     				= 'Die Energietechnik besch&auml;ftigt sich mit der Weiterentwicklung der Energieleitsysteme und Energiespeicher, welche f&uuml;r viele neue Technologien ben&ouml;tigt wird.';
$lang['tutorial_teil2_info15']     				= 'Hyperraumtechnik';
$lang['tutorial_teil2_info16']     				= 'Durch die Einbindung der 4. und 5. Dimension ist es nun m&ouml;glich einen neuartigen Antrieb zu erforschen, welcher sparsamer und leistungsf&auml;higer ist.';
$lang['tutorial_teil2_info17']     				= 'Verbrennungstriebwerk';
$lang['tutorial_teil2_info18']     				= 'Verbrennungstriebwerke basieren auf dem uralten Prinzip des R&uuml;ckstosses. Hocherhitzte Materie wird weggeschleudert und treibt das Schiff in die entgegengesetzte Richtung. Der Wirkungsgrad dieser Triebwerke ist eher gering, aber sie sind billig und zuverl&auml;ssig und ben&ouml;tigen kaum Wartung. Au&szlig;erdem verbrauchen sie weniger Raum und sind deshalb gerade auf kleineren Schiffen immer wieder zu finden. Da Verbrennungstriebwerke die Grundlage jeder Raumfahrt sind, sollten sie so fr&uuml;h wie m&ouml;glich erforscht werden. Die Weiterentwicklung dieser Triebwerke macht folgende Schiffe um 10% des Grundwertes pro Stufe schneller: Kleine und gro&szlig;e Transporter, Leichte J&auml;ger, Recycler und Spionagesonden.';
$lang['tutorial_teil2_info19']     				= 'Impulstriebwerk';
$lang['tutorial_teil2_info20']     				= 'Das Impulstriebwerk basiert auf dem R&uuml;cksto&szlig;prinzip, wobei die Strahlmasse zum Gro&szlig;teil als Abfallprodukt der zur Energiegewinnung verwendeten Kernfusion entsteht. Zus&auml;tzlich kann weitere Masse eingespritzt werden. Die Weiterentwicklung dieser Triebwerke macht folgende Schiffe um 20% des Grundwertes pro Stufe schneller: Bomber, Kreuzer, Schwere J&auml;ger und Kolonieschiffe. Interplanetarraketen k&ouml;nnen pro Stufe weiter fliegen.';
$lang['tutorial_teil2_info21']     				= 'Hyperraumantrieb';
$lang['tutorial_teil2_info22']     				= 'Durch eine Raumzeitverkr&uuml;mmung wird in unmittelbarer Umgebung eines Schiffes der Raum komprimiert, womit sich weite Strecken sehr schnell zur&uuml;cklegen lassen. Je h&ouml;her der Hyperraumantrieb entwickelt ist, desto h&ouml;her wird die Kompression des Raumes, wodurch sich pro Stufe die Geschwindigkeit der Schiffe die damit ausgestattet sind (Schlachtkreuzer, Schlachtschiffe, Zerst&ouml;rer und Todessterne) um 30% erh&ouml;ht. Voraussetzungen: Hyperraumtechnik (Stufe 3) Forschungslabor (Stufe 7).';
$lang['tutorial_teil2_info23']     				= 'Lasertechnik';
$lang['tutorial_teil2_info24']     				= '}Laser (Lichtverst&auml;rkung durch induzierte Strahlungsemission) erzeugen einen intensiven, energiereichen Strahl von koh&auml;rentem Licht. Diese Ger&auml;te finden in allen m&ouml;glichen Bereichen ihre Anwendung, von optischen Computern bis hin zu schweren Laserwaffen, die m&uuml;helos durch Raumschiffpanzerungen schneiden. Die Lasertechnik bildet einen wichtigen Grundstein f&uuml;r die Erforschung weiterer Waffentechnologien. Voraussetzungen: Forschungslabor (Stufe 1) Energietechnik (Stufe 2).';
$lang['tutorial_teil2_info25']     				= 'Ionentechnik';
$lang['tutorial_teil2_info26']     				= 'Wahrhaft t&ouml;dlicher Richtstrahl aus beschleunigten Ionen. Die beschleunigten Ionen richten beim Auftreffen auf ein Objekt einen riesigen Schaden an.';
$lang['tutorial_teil2_info27']     				= 'Plasmatechnik';
$lang['tutorial_teil2_info28']     				= 'Eine Weiterentwicklung der Ionentechnik, die nicht Ionen beschleunigt, sondern hochenergetisches Plasma. Das hochenergetische Plasma hat eine verheerende Wirkung beim Auftreffen auf ein Objekt.';
$lang['tutorial_teil2_info29']     				= 'Intergalaktisches Forschungsnetzwerk';
$lang['tutorial_teil2_info30']     				= 'Forscher verschiedener Planeten kommunizieren &uuml;ber dieses Netzwerk miteinander.Pro erforschtes Level, wird ein Forschungslabor vernetzt. Dabei werden immer die Labors der h&ouml;chsten Stufe dazugeschaltet.Das vernetzte Labor muss ausreichend ausgebaut sein um die anstehende Forschung selbst&auml;ndig durchf&uuml;hren zu k&ouml;nnen. Die Ausbaustufen aller beteiligten Labors werden im intergalaktischen Forschungsnetzwerk zusammen gez&auml;hlt.';
$lang['tutorial_teil2_info31']     				= 'Expeditionstechnik';
$lang['tutorial_teil2_info32']     				= 'Expeditionstechnik umfasst verschiedene Scanntechnologien und erm?glicht Raumschiffe diverser Gr??en mit einem Forschungsmodul auszur?sten. Dieses beinhaltet eine Datenbank und ein voll ausgestattetes mobiles Labor. Um bei gef?hrlichen Forschungsobjekten die Sicherheit des Schiffes zu gew?hren, verf?gt das Forschungsmodul ?ber eine eigene Energieversorgung und einen Energiefeldgenerator, der im Notfall das Forschungsmodul mit einem starken Kraftfeld umgeben kann.';
$lang['tutorial_teil2_info33']     				= 'Gravitonforschung';
$lang['tutorial_teil2_info34']     				= 'Ein Graviton ist ein Partikel, das keine Masse und keine Ladung besitzt, welche die Gravitationskraft bestimmt. Durch Abschuss einer konzentrierten Ladung von Gravitonen kann ein k&uuml;nstliches Gravitationsfeld errichtet werden, welches &auml;hnlich einem schwarzen Loch, Masse in sich hineinzieht, wodurch Schiffe oder auch Monde vernichtet werden k&ouml;nnen. Um eine ausreichende Menge Gravitonen herzustellen ben&ouml;tigt es riesige Mengen an Energie.';

//Tutorial 3 Anzeige--------------------------------------------------------------------------------------------------------
$lang['tutorial_teil3_info1']     				= 'Tutorial Teil 3';
$lang['tutorial_teil3_info2']     				= 'Hier findest du alles was du &uuml;ber die Raumschiffswerft wissen musst.';
$lang['tutorial_teil3_info3']     				= 'Kleiner Transporter';
$lang['tutorial_teil3_info4']     				= 'Transporter haben ungef&auml;hr die gleiche Gr&ouml;&szlig;e wie J&auml;ger, verzichten aber auf leistungsf&auml;hige Antriebe und Bordwaffen, um Platz f&uuml;r Frachtraum zu schaffen. Der kleine Transporter verf&uuml;gt &uuml;ber eine Ladekapazit&auml;t von 10.000 Ressourceneinheiten. Aufgrund ihrer geringen Feuerkraft werden Transporter oft von anderen Schiffen eskortiert.';
$lang['tutorial_teil3_info5']     				= 'Gro&szlig;er Transporter';
$lang['tutorial_teil3_info6']     				= 'Dieses Schiff hat kaum Waffen oder andere Technologien an Bord. Aus diesem Grunde sollten sie nie alleine losgeschickt werden. Der gro&szlig;e Transporter dient durch sein hochentwickeltes Verbrennungstriebwerk als schneller Ressourcenlieferant zwischen den Planeten und nat&uuml;rlich begleitet er die Flotten auf ihren &uuml;berf&auml;llen feindlicher Planeten, um m&ouml;glichst viele Ressourcen zu erobern, der Gro&szlig;e Transporter verf&uuml;gt &uuml;ber eine Ladekapazit&auml;t von 50.000 Ressourceneinheiten.';
$lang['tutorial_teil3_info7']     				= 'Leichter J&auml;ger';
$lang['tutorial_teil3_info8']     				= 'Der leichte J&auml;ger ist ein wendiges Schiff, das auf fast jedem Planeten vorgefunden wird. Die Kosten sind nicht besonders hoch, Schildst&auml;rke und Ladekapazit&auml;t sind allerdings sehr gering.';
$lang['tutorial_teil3_info9']     				= 'Schwerer J&auml;ger';
$lang['tutorial_teil3_info10']     				= 'Bei der Weiterentwicklung des leichten J&auml;gers kamen die Forscher zu einem Punkt, bei welchem der konventionelle Antrieb nicht mehr ausreichend Leistungen erbrachte. Um das neue Schiff optimal fortbewegen zu k&ouml;nnen wurde zum ersten Mal der Impulsantrieb genutzt. Dieses erh&ouml;hte zwar die Kosten, er&ouml;ffnete aber auch neue M&ouml;glichkeiten. Durch die Einsetzung dieses Antriebes blieb mehr Energie f&uuml;r Waffen und Schilde &uuml;brig, au&szlig;erdem wurden f&uuml;r diese neue J&auml;gergattung auch qualitativ hochwertigere Materialien verwendet. Dies f&uuml;hrte zu einer verbesserten strukturellen Integrit&auml;t und einer h&ouml;heren Feuerkraft, was ihn im Kampf zu einer immens gr&ouml;&szlig;eren Bedrohung macht als sein leichtes Pendant. Durch diese &auml;nderungen stellt der schwere J&auml;ger eine neue &auml;ra der Schiffstechnologie dar, welche die Grundlage f&uuml;r die Kreuzertechnologie ist.';
$lang['tutorial_teil3_info11']     				= 'Kreuzer';
$lang['tutorial_teil3_info12']     				= 'Mit der Entwicklung der schweren Laser und der Ionenkanonen kamen die J&auml;ger immer mehr in Bedr&auml;ngnis. Trotz vieler Modifikationen konnte die Waffenst&auml;rke und die Panzerung nicht so weit gesteigert werden, um diesen Verteidigungsgesch&uuml;tzen wirksam begegnen zu k&ouml;nnen. Deshalb entschied man sich, eine neue Schiffsklasse zu konstruieren, die mehr Panzerung und mehr Feuerkraft in sich vereinte. Der Kreuzer war geboren. Kreuzer sind fast dreimal so stark gepanzert wie schwere J&auml;ger und verf&uuml;gen &uuml;ber mehr als die doppelte Schusskraft. Zudem sind sie sehr schnell. Gegen mittlere Verteidigung gibt es keine bessere Waffe. Kreuzer beherrschten fast ein Jahrhundert lang unumschr&auml;nkt das All. Mit dem Aufkommen der Gau&szlig;gesch&uuml;tze und Plasmawerfer endete ihre Vorherrschaft. Jedoch werden sie auch heute noch gerne gegen J&auml;gerverb&auml;nde eingesetzt.';
$lang['tutorial_teil3_info13']     				= 'Schlachtschiff';
$lang['tutorial_teil3_info14']     				= 'Schlachtschiffe bilden meist das R&uuml;ckgrat einer Flotte. Ihre schweren Gesch&uuml;tze, die hohe Geschwindigkeit und der gro&szlig;e Frachtraum machen sie zu ernst zu nehmenden Gegnern.';
$lang['tutorial_teil3_info15']     				= 'Kolonieschiff';
$lang['tutorial_teil3_info16']     				= 'Dieses gut gepanzerte Schiff dient der Eroberung neuer Planeten, was f&uuml;r ein aufstrebendes Imperium unerl&auml;sslich ist. Das Schiff wird auf der neuen Kolonie als Rohstofflieferant genutzt, in dem es wieder auseinander gebaut wird und alles wiederverwertbare Material f&uuml;r die Erschlie&szlig;ung der Neuen Welt genutzt wird. Pro Imperium k&ouml;nnen inklusive Hauptplanet maximal 9 Planeten kolonisiert werden.';
$lang['tutorial_teil3_info17']     				= 'Recycler';
$lang['tutorial_teil3_info18']     				= 'Die Weltraumgefechte nahmen immer gr&ouml;&szlig;ere Ausma&szlig;e an. Tausende Schiffe wurden zerst&ouml;rt, aber die dadurch entstehenden Tr&uuml;mmerfelder schienen f&uuml;r immer verloren. Normale Transporter konnten sich nicht nahe genug an diese Felder heran bewegen, ohne durch kleinere Tr&uuml;mmer riesigen Schaden zu nehmen. Mit einer neuen Entwicklung im Bereich der Schildtechnologie konnte dieses Problem effizient beseitigt werden, es entstand eine neue Schiffsklasse, &auml;hnlich dem gro&szlig;en Transporter, der TF Sammler . Mit dessen Hilfe konnten die scheinbar verlorenen Ressourcen doch noch verwertet werden. Die kleinen Tr&uuml;mmer stellten aufgrund der neuen Schilde auch keine Gefahr mehr dar. Leider ben&ouml;tigen diese Vorrichtungen Platz, dadurch ist seine Ladekapazit&auml;t auf 40.000 beschr&auml;nkt.';
$lang['tutorial_teil3_info19']     				= 'Spionagesonde';
$lang['tutorial_teil3_info20']     				= 'Spionagesonden sind kleine wendige Drohnen, welche &uuml;ber weite Entfernungen hinweg Daten &uuml;ber Flotten und Planeten liefern. Ihr Hochleistungstriebwerk erm&ouml;glicht ihnen weite Strecken in wenigen Sekunden zur&uuml;ck zu legen. Einmal in der Umlaufbahn eines Planeten angekommen verweilen sie dort kurz um Daten zu sammeln. W&auml;hrend dieser Zeit sind sie vom Feind relativ leicht entdeck- und angreifbar. Um Platz zu sparen wurde auf Panzerung, Schilde und Waffen verzichtet, was die Sonden, wenn sie einmal entdeckt wurden, zu leichten Zielen macht.';
$lang['tutorial_teil3_info21']     				= 'Bomber';
$lang['tutorial_teil3_info22']     				= 'Der Bomber wurde speziell entwickelt um die Verteidigung eines Planeten zu zerst&ouml;ren. Mit Hilfe einer lasergesteuerten Zielvorrichtung wirft er zielgenau Plasmabomben auf die Planetenoberfl&auml;che und richtet so einen verheerenden Schaden bei Verteidigungsanlagen an.';
$lang['tutorial_teil3_info23']     				= 'Solarsatellit';
$lang['tutorial_teil3_info24']     				= 'Solarsatelliten werden in eine geostation&auml;re Umlaufbahn um einen Planeten geschossen. Sie b&uuml;ndeln Sonnenenergie und transferieren sie zu einer Bodenstation. Die Effizienz der Solarsatelliten h&auml;ngt von der St&auml;rke der Sonneneinstrahlung ab. Grunds&auml;tzlich ist die Energieausbeute auf sonnennahen Orbits gr&ouml;&szlig;er als auf Planeten mit sonnenfernen Orbit. Durch ihr gutes Preis/Leistungsverh&auml;ltnis l&ouml;sen Solarsatelliten die Energieprobleme vieler Welten. Aber Vorsicht: Solarsatelliten k&ouml;nnen im Kampf zerst&ouml;rt werden.';
$lang['tutorial_teil3_info25']     				= 'Zerst&ouml;rer';
$lang['tutorial_teil3_info26']     				= 'Der Zerst&ouml;rer ist der K&ouml;nig unter den Kriegsschiffen. Seine Multiphalanx Ionen-, Plasma- und Gau&szlig;gesch&uuml;tzt&uuml;rme k&ouml;nnen durch ihre verbesserten Anpeilungssensoren fast 99% der verteidigenden leichten Laser treffen. Da der Zerst&ouml;rer sehr gro&szlig; ist, ist seine Man&ouml;vrierf&auml;higkeit stark eingeschr&auml;nkt, wodurch er im Kampf eher einer Kampfstation gleicht, als einem Kampfschiff. So hoch wie seine Kampfkraft ist auch sein Verbrauch an Deuterium.';
$lang['tutorial_teil3_info27']     				= 'Todesstern';
$lang['tutorial_teil3_info28']     				= 'Der Todesstern ist mit einer riesigen Gravitonkanone bewaffnet, die Schiffe so gro&szlig; wie Zerst&ouml;rer oder sogar Monde zerst&ouml;ren kann. Da daf&uuml;r eine hohe Menge an Energie ben&ouml;tigt wird, besteht er fast nur aus Generatoren. Lediglich riesige Sternenreiche k&ouml;nnen &uuml;berhaupt die Ressourcen und Arbeiter aufbringen, um dieses mondgro&szlig;e Schiff zu bauen.';
$lang['tutorial_teil3_info29']     				= 'Schlachtkreuzer';
$lang['tutorial_teil3_info30']     				= 'Dieses filigrane Schiff eignet sich hervorragend zum Zerst&ouml;ren feindlicher Flottenverb&auml;nde. Mit seinen hochentwickelten Lasergesch&uuml;tzen ist es in der Lage, eine grosse Zahl angreifender Schiffe gleichzeitig zu bek&auml;mpfen. Durch seine schlanke Bauform und die starken Bewaffnung ist die Ladekapazit&auml;t begrenzt. Dies wird jedoch durch den verbrauchsarmen Hyperraumantrieb wieder ausgeglichen.';

//Tutorial 4 Anzeige--------------------------------------------------------------------------------------------------------
$lang['tutorial_teil4_info1']     				= 'Tutorial Teil 4';
$lang['tutorial_teil4_info2']     				= 'Hier findest du alles was du &uuml;ber die Verteidigunganlage wissen musst.';
$lang['tutorial_teil4_info3']     				= 'Raketenwerfer';
$lang['tutorial_teil4_info4']     				= 'Der Raketenwerfer ist eine einfache aber kosteng&uuml;nstige Verteidigungsm&ouml;glichkeit. Da er nur eine Weiterentwicklung gew&ouml;hnlicher ballistischer Feuerwaffen ist, ben&ouml;tigt er keine weitere Forschung. Seine geringen Herstellungskosten rechtfertigen seinen Einsatz gegen kleinere Flotten, er verliert aber mit der Zeit an Bedeutung. Sp&auml;ter wird er nur noch als Schussfang hinter gro&szlig;en Gesch&uuml;tzen eingesetzt. Verteidigungsanlagen deaktivieren sich, sobald sie zu stark besch&auml;digt sind. Nach einer Schlacht betr&auml;gt die Chance bis zu 70%, dass sich ausgefallene Verteidigungsanlagen wieder Instand setzen lassen.';
$lang['tutorial_teil4_info5']     				= 'Leichtes Lasergesch&uuml;tz';
$lang['tutorial_teil4_info6']     				= 'Um die enormen Fortschritte im Bereich der Raumschifftechnologie kompensieren zu k&ouml;nnen, mussten die Forscher eine Verteidigungsanlage entwickeln, welche auch mit gr&ouml;&szlig;eren und besser ausger&uuml;steten Schiffen bzw. Flotten zurechtkommt. Dies war die Geburtsstunde des leichten Lasers. Durch den konzentrierten Beschuss eines Ziels mit Photonen konnte eine wesentlich gr&ouml;&szlig;ere Schadenswirkung erzielt werden als mit gew&ouml;hnlichen ballistischen Waffen. Um der gr&ouml;&szlig;eren Feuerkraft der neuen Schiffstypen widerstehen zu k&ouml;nnen wurde er au&szlig;erdem mit verbesserten Schilden ausgestattet. Damit die Produktionskosten dennoch gering gehalten werden konnten wurde die Struktur nicht weiter verst&auml;rkt. Der leichte Laser besitzt das beste Preis-/Leistungsverh&auml;ltnis &uuml;berhaupt und ist dadurch auch f&uuml;r weiter fortgeschrittene Zivilisationen interessant. Verteidigungsanlagen deaktivieren sich, sobald sie zu stark besch&auml;digt sind. Nach einer Schlacht betr&auml;gt die Chance bis zu 70%, dass sich die zerst&ouml;rten Verteidigungsanlagen wieder Instand setzen lassen.';
$lang['tutorial_teil4_info7']     				= 'Schweres Lasergesch&uuml;tz';
$lang['tutorial_teil4_info8']     				= 'Der schwere Laser stellt die konsequente Weiterentwicklung des Designs des leichten Lasers dar. Die Struktur wurde verst&auml;rkt und mit neuen Materialien verbessert. Die H&uuml;lle konnte so wesentlich widerstandsf&auml;higer gemacht werden. Gleichzeitig wurden auch das Energiesystem und der Zielcomputer verbessert, so dass ein schwerer Laser wesentlich mehr Energie auf ein Ziel konzentrieren kann. Verteidigungsanlagen deaktivieren sich, sobald sie zu stark besch&auml;digt sind. Nach einer Schlacht betr&auml;gt die Chance bis zu 70%, dass sich ausgefallene Verteidigungsanlagen wieder Instand setzen lassen.';
$lang['tutorial_teil4_info9']     				= 'Gau&szlig;kanone';
$lang['tutorial_teil4_info10']     				= 'Projektilwaffen galten lange Zeit neben der moderneren Kernfusions- und Energietechnik, der Entwicklung des Hyperraumantriebs und immer besserer Panzerungen als antiquiert, bis eben genau die Energietechnik, die sie einst verdr&auml;ngt hatte, ihr wieder zu ihrem angestammten Platz verhalf. Das Prinzip war eigentlich schon aus dem 20. und 21. Jahrhundert der Erde bekannt - der Teilchenbeschleuniger. Eine Gau&szlig;kanone ist eigentlich nichts anderes als eine erheblich gr&ouml;&szlig;ere Version dieser Konstruktion. Tonnenschwere Geschosse werden unter gigantischem elektrischem Aufwand magnetisch beschleunigt und haben M&uuml;ndungsgeschwindigkeiten, die die Schmutzteilchen in der Luft um das Geschoss verbrennen lassen und der R&uuml;cksto&szlig; bringt die Erde zum beben. Dieser Durchschlagskraft k&ouml;nnen auch aktuelle Panzerungen und Schilde nur schwer widerstehen, und es kommt nicht selten vor, dass das Ziel einfach durchschlagen wird. Verteidigungsanlagen deaktivieren sich, sobald sie zu stark besch&auml;digt sind. Nach einer Schlacht betr&auml;gt die Chance bis zu 70%, dass sich ausgefallene Verteidigungsanlagen wieder Instand setzen lassen.';
$lang['tutorial_teil4_info11']     				= 'Ionengesch&uuml;tz';
$lang['tutorial_teil4_info12']     				= 'Im 21. Jahrhundert der Erde gab es etwas, das allgemein als EMP bekannt war. EMP steht f&uuml;r Elektromagnetischer Puls, der die Eigenschaft hat, in alle Schaltkreise zus&auml;tzliche Spannungen zu induzieren und somit massenhafte St&ouml;rungen zu verursachen, die alle empfindlichen Ger&auml;te zerst&ouml;ren k&ouml;nnen. Damals waren EMP - Waffen meistens noch auf Raketen- und Bombenbasis, auch in Verbindung mit Nuklearwaffen. Mittlerweile wurde der EMP st&auml;ndig weiterentwickelt, da man in ihm ein gro&szlig;es Potential sah, Ziele nicht zu zerst&ouml;ren, aber kampf- und man&ouml;vrierunf&auml;hig zu machen, so dass einer &uuml;bernahme nichts mehr im Wege stand. Die bisher h&ouml;chste Form einer EMP - Waffe stellt das Ionengesch&uuml;tz dar. Es schleudert eine Welle von Ionen (elektrisch geladene Teilchen) auf das Ziel, welche die Schilde destabilisiert und alle Elektronik - sofern diese nicht massiv abgeschirmt ist - besch&auml;digt, was nicht selten einer v&ouml;lligen Zerst&ouml;rung gleichkommt. Die kinetische Durchschlagskraft kann vernachl&auml;ssigt werden. Die Ionentechnik wird auch auf Kreuzern eingesetzt, jedoch auf keinem anderen Schiffstyp, da der Energieverbrauch der Ionengesch&uuml;tze enorm ist und es in einem Gefecht h&auml;ufig darauf ankommt, das Ziel zu zerst&ouml;ren und nicht nur zu paralysieren. Verteidigungsanlagen deaktivieren sich, sobald sie zu stark besch&auml;digt sind. Nach einer Schlacht betr&auml;gt die Chance bis zu 70%, dass sich ausgefallene Verteidigungsanlagen wieder Instand setzen lassen.';
$lang['tutorial_teil4_info13']     				= 'Plasmawerfer';
$lang['tutorial_teil4_info14']     				= 'Die Lasertechnik war mittlerweile nahezu perfektioniert, die Ionentechnik hatte ein Endstadium erreicht und es galt mittlerweile als praktisch unm&ouml;glich, auch aus nur einem Waffensystem qualitativ gesehen noch mehr Effektivit&auml;t herauszubekommen. Doch all dies sollte sich &auml;ndern, als man auf die Idee kam, beide Systeme miteinander zu kombinieren. Schon aus der Kernfusionstechnik bekannt, erhitzen Laser Teilchen ( meistens Deuterium ) auf extrem hohe Temperaturen, die schon einmal in die Millionen Grad gehen. Die Ionentechnik tr&auml;gt ihren Teil in Form von elektrischer Aufladung, Stabilisierungsfeldern und Beschleunigern bei. Wird die abzufeuernde Ladung gen&uuml;gend erhitzt, unter Druck gesetzt und ionisiert, jagt man sie mittels Beschleunigern in die Weiten des Alls Richtung Ziel hinaus. Der gr&uuml;nlich gl&uuml;hende Plasmastrahl bietet einen imposanten Anblick, es fragt sich aber, ob die Crew des Zielschiffes lange an ihm Gefallen haben wird, wenn in wenigen Sekunden die H&uuml;lle zerfetzt und die Elektronik geschmort wird... Der Plasmawerfer gilt als eine der gef&uuml;rchtetsten Waffen &uuml;berhaupt, und diese Technik hat auch ihren Preis. Verteidigungsanlagen deaktivieren sich, sobald sie zu stark besch&auml;digt sind. Nach einer Schlacht betr&auml;gt die Chance bis zu 70%, dass sich ausgefallene Verteidigungsanlagen wieder Instand setzen lassen.';
$lang['tutorial_teil4_info15']     				= 'Kleine Schildkuppel';
$lang['tutorial_teil4_info16']     				= 'Lange bevor die Schildgeneratoren klein genug waren, um auf Schiffen Einsatz zu finden, existierten bereits riesige Generatoren auf der Oberfl&auml;che von Planeten. Diese umh&uuml;llen den ganzen Planeten mit einem Kraftfeld, welches ungeheuere Mengen an Energie absorbieren kann, bevor es zusammenbricht. Kleinere Angriffsflotten scheitern immer wieder an diesen Schildkuppeln. Mit zunehmender technologischer Entwicklung k&ouml;nnen diese Schilde noch verst&auml;rkt werden. Sp&auml;ter kann man sogar eine gro&szlig;e Schildkuppel bauen, die noch st&auml;rker ist. Pro Planet kann nur eine einzige kleine Schildkuppel gebaut werden.';
$lang['tutorial_teil4_info17']     				= 'Gro&szlig;e Schildkuppel';
$lang['tutorial_teil4_info18']     				= 'Die Weiterentwicklung der kleinen Schildkuppel. Sie basiert auf den gleichen Technologien kann aber wesentlich mehr Energie einsetzen um feindliche Angriffe abzuhalten.';
$lang['tutorial_teil4_info19']     				= 'Bodenluft Abfangrakete';
$lang['tutorial_teil4_info20']     				= 'Abfangraketen zerst&ouml;ren angreifende Intercontineltalraketen. Jede Bodenluft rakete zerst&ouml;rt eine Interplanetarrakete.';
$lang['tutorial_teil4_info21']     				= 'Intercontinental Rakete';
$lang['tutorial_teil4_info22']     				= 'Intercontinentalraketen zerst&ouml;ren die gegnerische Verteidigung, k&ouml;nnen allerdings durch Abfangraketen zerst&ouml;rt werden! Von Interplanetarraketen zerst&ouml;rte Verteidigungsanlagen bauen sich nicht wieder auf.';

//Tutorial 5 Anzeige--------------------------------------------------------------------------------------------------------
$lang['tutorial_teil5_info1']     				= 'Tutorial Teil 5';
$lang['tutorial_teil5_info2']     				= 'Dieser Teil befasst sich mit der Verteidigung deines eigenen Planeten, mit der Galaxieansicht und den M&ouml;glichkeiten der eigenen Flotte.';
$lang['tutorial_teil5_info3']     				= 'Die Galaxieansicht';
$lang['tutorial_teil5_info4']     				= 'Die Galaxieansicht dient dazu andere Spieler zu lokalisieren. Gleichzeitig werden hier detaillierte Information zu anderen Spielern, Planeten und Allianzen angezeigt. Gleichzeitig ist es m&ouml;glich teile seiner Flotte direkt aus der Ansicht zu verschicken. Zus&auml;tzlich kann man hier auch Kontakt zu anderen Spielern aufnehmen und andere Planeten ausspionieren.';
$lang['tutorial_teil5_info5']     				= 'Versenden von Flotten';
$lang['tutorial_teil5_info6']     				= 'Es gibt zwei M&ouml;glichkeiten Flotten zu versenden. Die erste ist direckt &uuml;ber die Galaxieansicht oder &uuml;ber den Men&uuml;punkt "Flotte". Zuerst m&uuml;ssen die Zielkoordinaten und die Reisegeschwindigkeit festgelegt werden. Die Koordinaten kannst du entweder &uuml;ber die Galaxieansicht automatisch eintragen lassen oder du tr&auml;gst sie von Hand ein. Danach muss angegeben werden, was f&uuml;r Schiffe fliegen sollen und wie  viele  Schiffe an der Mission teilnehmen sollen. Danach muss die Mission ausgew&auml;hlt   werden. Hierbei stehen Folgende zur Auswahl, <u>Transportieren:</u> Hierbei fliegen deine Schiffe Punkt A an, laden ihre Ressourcen aus und Fliegen wieder zum Ausgangspunkt zur&uuml;ck. <u>Stationieren:</u> Hierbei fliegen deine Schiffe Punkt A an, laden ihre Ressourcen aus und verbleiben bei Punkt A. <u>Angreifen:</u> Hierbei fliegen deine Schiffe Punkt B an K&auml;mpfen mit der an Punkt B Stationierten Flotte und Verteidigungsanlagen und nehmen im Falle eines Sieges einen bestimmten Anteil an Ressourcen mit &uuml;ber die Punkt B verf&uuml;gt. Diese Ressourcen stehen dir auf dem Ausgangsplaneten der Flotte nach der R&uuml;ckkehr zur Verf&uuml;gung.';
$lang['tutorial_teil5_info7']     				= 'Die Verteidigung';
$lang['tutorial_teil5_info8']     				= 'Um deinen Planeten zu sch&uuml;tzen stehen dir nach dem Bau der Raumschiffwerft verschiedenste Verteidigungsanlagen zur Verf&uuml;gung. Vorausgesetzt, dass du die notwendige Technologie erforscht hast. Verteidigungsanlagen unterst&uuml;tzen die eigene Flotte bei einem Kampf im Orbit um deinen Planeten. Anders als die Flotte baue sich 70% der zerst&ouml;rten Verteidigungsanlagen nach einem Kampf automatisch wieder auf.';

//Tutorial 6 Anzeige--------------------------------------------------------------------------------------------------------
$lang['tutorial_teil6_info1']     				= 'Tutorial Teil 6';
$lang['tutorial_teil6_info2']     				= 'Dieser Teil befasst sich mit den gebr&auml;uchlichen Abk&uuml;rzungen im Game';

//Tutorial 7 Anzeige--------------------------------------------------------------------------------------------------------
$lang['tutorial_teil7_info1']     				= 'Tutorial Teil 7';
$lang['tutorial_teil7_info2']     				= 'Dieser Teil befasst sich mit dem s.g. Saven seiner eigenen Flotte.';
$lang['tutorial_teil7_info3']     				= 'Eine gro&szlig;e Anzahl an Verteidigungsanlagen schreckt nicht jeden Spieler ab. Im Gegenteil. Einige Spieler werden durch eine gro&szlig;e Anzahl von Verteidigungsanlagen sogar angelockt. In den so genannten Deff-ins-Tr&uuml;mmerfeld Unis ist es erst recht nicht ratsam eine gro&szlig;e Anzahl an Verteidigungsanlagen zu bauen, da diese nun bei der Zerst&ouml;rung in das Tr&uuml;mmerfeld &uuml;bergehen.<br>Hinzu kommt auch noch, dass es Interplanetar Raketen gibt. Diese Raketen sind einzig und alleine auf die Zerst&ouml;rung von Verteidigungsanlagen ausgerichtet. Mit einem gut gezielten Angriff mit dieses Raketen kann die Gefahr f&uuml;r die eigene Flotte stark vermindern.<br>Auch eine gro&szlig;e Flotte h&auml;lt nur Spieler ab, deren Flotte zu schwach ist um. Spieler die eine st&auml;rkere Flotte haben als du werden allerdings gerne vorbei kommen um deine Flotte zu vernichten und das entstehende Tr&uuml;mmerfeld einzusacken.<br>Die wohl beste M&ouml;glichkeit seine Schiffe und Ressourcen zu sch&uuml;tzen besteht darin, dass du deine Flotte + die gesamten Ressourcen auf deinem Planeten zu einem anderen Schickst. Angriffe im freien Flug sind n&auml;mlich nicht m&ouml;glich.';
$lang['tutorial_teil7_info4']     				= 'Saven ist die beste Deff';
$lang['tutorial_teil7_info5']     				= 'Das s.g. Saven ist einer der wichtigsten Bestandteile des Games. Leider beherrschen viele Spieler das Saven nicht. Aus diesem Grund hier eine Erkl&auml;rung: Es gibt mehrere M&ouml;glichkeiten seine Schiffe und Ressourcen vor &uuml;bergriffen Feindlicher Flotten zu sch&uuml;tzen. Dabei sind einige sehr sicher und andere beinhalten Risiken.<br>Die erste Methode ist das Stationieren-R&uuml;ckruf Saven. Hierbei schickt der Spieler seine Flotte auf einen seiner Planeten mit dem Auftrag Stationieren. Nach einiger Zeit bricht der Spieler den Flug ab, da der R&uuml;ckflug einer Stationierung in der Ortung der Sensorphalanx nicht mehr sichtbar ist. Diese Methode ist nicht zu 100% sicher, da Gegner aus deiner Vergangenen Flugzeit (mit der Sensorphalanx zu erfahren) die Zeit errechnen k&ouml;nnen die deine Flotte f&uuml;r den R&uuml;ckflug ben&ouml;tigt.<br>Eine der wohl am meisten Genutzten   M&ouml;glichkeiten ist der Flug von einem Mond oder Planeten zu einem Tr&uuml;mmerfeld. Hierbei ist der Flug von einem Mond auf das Tr&uuml;mmerfeld wesentlich sicherer, da Monde nicht per Sensorphalanx gescannt werden k&ouml;nnen. Es gibt allerdings ist auch diese M&ouml;glichkeit nicht zu 100% sicher, da Spieler die Tr&uuml;mmerfelder &uuml;berwachen k&ouml;nnen. Aus der Zeit des Abbaus und der Entfernung   zu deinem Planeten k&ouml;nnen sie die ungef&auml;hre Flugzeit ermitteln, die deine Flotte noch unterwegs ist. Eine M&ouml;glichkeit   sich hiervor zu sch&uuml;tzen ist das versenden von s.g. Geisterrecyclern. Diese werden einige Zeit vor der normalen Flotte ausgesendet und so verschwindet das Tr&uuml;mmerfeld schon bevor die eigentliche Flotte angekommen ist. Eine weitere Methode besteht darin, so kleine Tr&uuml;mmerfelder   zu schie&szlig;en, dass diese nicht in der Galaxieansicht   auftauchen. Dies ist mit Spionagesonden   m&ouml;glich. In der Galaxieansicht erscheint kein Tr&uuml;mmerfeld, doch f&uuml;r den der wei&szlig; dass dort Spionagesonden vernichtet wurden bietet dieses unsichtbare Tr&uuml;mmerfeld   eine ideale Save M&ouml;glichkeit.<br>Die Methode die wohl am sichersten ist, ist das Stationieren von Mond zu Mond. Dieser Flug kann nicht per Sensorphalanx geortet werden und auch das beobachten von Tr&uuml;mmerfeldern ist hier nutzlos. Die einzige   M&ouml;glichkeit diesen Flug abzufangen besteht darin, einen der Monde zu zerst&ouml;ren. Was  bei gro&szlig;en Monden allerdings sehr sehr Teuer und unwahrscheinlich ist.';

//----Script Ende-----------------------------------------------------------------------------------------------------------
?>